name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: zm99by
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming, markup
          plugin_languages_colors: github
          plugin_languages_limit: 8
          filename: github-metrics.svg
